# Generated by Django 3.0.5 on 2020-07-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idiscount', models.IntegerField()),
                ('ibrand', models.CharField(max_length=10)),
                ('ipic', models.ImageField(default='', upload_to='imgs')),
                ('iname', models.CharField(max_length=50)),
                ('idesc', models.CharField(max_length=200)),
                ('iprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oneplus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odiscount', models.IntegerField()),
                ('obrand', models.CharField(max_length=10)),
                ('opic', models.ImageField(default='', upload_to='imgs')),
                ('oname', models.CharField(max_length=50)),
                ('odesc', models.CharField(max_length=200)),
                ('oprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdiscount', models.IntegerField()),
                ('pbrand', models.CharField(max_length=10)),
                ('ppic', models.ImageField(default='', upload_to='imgs')),
                ('pname', models.CharField(max_length=50)),
                ('pdesc', models.CharField(max_length=200)),
                ('pprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idiscount', models.IntegerField()),
                ('ibrand', models.CharField(max_length=10)),
                ('ipic', models.ImageField(default='', upload_to='imgs')),
                ('iname', models.CharField(max_length=50)),
                ('idesc', models.CharField(max_length=200)),
                ('iprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=80)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=40)),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
