# Generated by Django 3.0.5 on 2020-07-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delldiscount', models.IntegerField()),
                ('dellbrand', models.CharField(max_length=10)),
                ('dellpic', models.ImageField(default='', upload_to='imgs')),
                ('dellname', models.CharField(max_length=50)),
                ('delldesc', models.CharField(max_length=200)),
                ('dellprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpdiscount', models.IntegerField()),
                ('hpbrand', models.CharField(max_length=10)),
                ('hppic', models.ImageField(default='', upload_to='imgs')),
                ('hpname', models.CharField(max_length=50)),
                ('hpdesc', models.CharField(max_length=200)),
                ('hpprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jdiscount', models.IntegerField()),
                ('jbrand', models.CharField(max_length=10)),
                ('jpic', models.ImageField(default='', upload_to='imgs')),
                ('jname', models.CharField(max_length=50)),
                ('jdesc', models.CharField(max_length=200)),
                ('jprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lenovo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldiscount', models.IntegerField()),
                ('lbrand', models.CharField(max_length=10)),
                ('lpic', models.ImageField(default='', upload_to='imgs')),
                ('lname', models.CharField(max_length=50)),
                ('ldesc', models.CharField(max_length=200)),
                ('lprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shdiscount', models.IntegerField()),
                ('shbrand', models.CharField(max_length=10)),
                ('shpic', models.ImageField(default='', upload_to='imgs')),
                ('shname', models.CharField(max_length=50)),
                ('shdesc', models.CharField(max_length=200)),
                ('shprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoediscount', models.IntegerField()),
                ('shoebrand', models.CharField(max_length=10)),
                ('shoepic', models.ImageField(default='', upload_to='imgs')),
                ('shoename', models.CharField(max_length=50)),
                ('shoedesc', models.CharField(max_length=200)),
                ('shoeprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdiscount', models.IntegerField()),
                ('tbrand', models.CharField(max_length=10)),
                ('tpic', models.ImageField(default='', upload_to='imgs')),
                ('tname', models.CharField(max_length=50)),
                ('tdesc', models.CharField(max_length=200)),
                ('tprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wdiscount', models.IntegerField()),
                ('wbrand', models.CharField(max_length=10)),
                ('wpic', models.ImageField(default='', upload_to='imgs')),
                ('wname', models.CharField(max_length=50)),
                ('wdesc', models.CharField(max_length=200)),
                ('wprice', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='samsung',
            old_name='ibrand',
            new_name='sbrand',
        ),
        migrations.RenameField(
            model_name='samsung',
            old_name='idesc',
            new_name='sdesc',
        ),
        migrations.RenameField(
            model_name='samsung',
            old_name='idiscount',
            new_name='sdiscount',
        ),
        migrations.RenameField(
            model_name='samsung',
            old_name='iname',
            new_name='sname',
        ),
        migrations.RenameField(
            model_name='samsung',
            old_name='ipic',
            new_name='spic',
        ),
        migrations.RenameField(
            model_name='samsung',
            old_name='iprice',
            new_name='sprice',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='uid',
        ),
        migrations.AddField(
            model_name='signup',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
